# Special Numpy Arrays

### Array filled with the 0s.

In [3]:
import numpy as np 

a=np.zeros(5)
b=np.zeros((3,4))
print(a)
print()
print(b)

[0. 0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### Array filled with 1s.

In [13]:
import numpy as np

c=np.ones(4)
d=np.ones((2,4))
print(c)
print()
print(d)

[1 2 3 4]

[[[1 2 3 4]
  [5 6 7 8]]]


### Empty array
- It print the array of elements with the values, which were previouslyy allocated to that memory location.

In [6]:
import numpy as np

e=np.empty(5)
f=np.empty((3,4))
print(e)
print()
print(f)

[4.9406565e-324 3.9525252e-323 3.9525252e-323 3.9525252e-323
 7.7258396e-304]

[[4.45057637e-308 1.78021527e-306 8.45549797e-307 1.37962049e-306]
 [1.11260619e-306 1.78010255e-306 9.79054228e-307 4.45057637e-308]
 [8.45596650e-307 9.34602321e-307 4.94065646e-322 8.34443015e-308]]


### Arange function
- This funcion is only applicable for 1D array. For multi dimensional array, reshape function is used.

In [21]:
import numpy as np

g=np.arange(6)
h=g.reshape((2,3))
print(g)
print()
print(h)

[0 1 2 3 4 5]

[[0 1 2]
 [3 4 5]]


### Diagonal Matrix
- All the diagonal elements are initialised with 1 and rest are with 0.

In [18]:
h=np.eye(4)
i=np.eye(3,6)
print(h)
print()
print(i)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]


### Linspace Function
- It is used to obtain the particular no of elements between two numbers.
- It only applicable for 1D array. For multi dimensional array, we need to reshape the array.

In [27]:
j=np.linspace(start=0,stop=22,num=12)
k=j.reshape((4,3))
print(j)
print()
print(k)

[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18. 20. 22.]

[[ 0.  2.  4.]
 [ 6.  8. 10.]
 [12. 14. 16.]
 [18. 20. 22.]]
