# Applying Arithmetic Operations in Array.

In [1]:
import numpy as np 
var1=np.array([1,2,3,4,5])

varadd=var1+3

print(varadd)

[4 5 6 7 8]


In [2]:
import numpy as np 
var1=np.array([1,2,3,4,5])

varsub=var1-3

print(varsub)

[-2 -1  0  1  2]


- We can even perform the operations between two arrays too. But the size of the arrays should be same.

In [5]:
import numpy as np 
var1=np.array([1,2,3,4,5])
var2=np.array([1,2,3,4,5])

varadd=var1+var2

print(varadd)

[ 2  4  6  8 10]


- We can also use the inbuilt Numpy functions for the arithmetic operations.

In [7]:
import numpy as np
var1=np.array([1,2,3,4,5])
var2=np.array([11,22,33,44,55])
var3=np.array([1,1,1,1,1])
var4=2

varadd=np.add(var1,var2)
varmul=np.multiply(var1,var4)
varpow=np.power(var1,var4)

print(varadd,"\n")
print(varmul,"\n")
print(varpow)


[12 24 36 48 60] 

[ 2  4  6  8 10] 

[ 1  4  9 16 25]


In [8]:
import numpy as np 
var1=np.array([1,2,3,4,5])

newvar=np.mod(var1,2)

print(newvar)

[1 0 1 0 1]


In [14]:
import numpy as np 
var1=np.array([1,2,3,4,5])

newvar=np.reciprocal(var1)

print(newvar)
print(newvar.dtype)

[1 0 0 0 0]
int32
