# Broadcasting 

- When both the arrays have same order (shape).

In [14]:
import numpy as np 

var1=np.array([[1,2,3],[4,5,6]])
var2=np.array([[1,2,3],[5,6,7]])

print(var1+var2)

[[ 2  4  6]
 [ 9 11 13]]


- Dimensions of the arrays should be same, but their shapes can be different.
- Start from right side.
- For the each pair, compatibility will exist if both of them are same or one of them is 1.
ex:- 
    - (2,1) and (1,2) are compatible.
    - (3,1) and (1,4) are compatible.
    - (4,3) and (1,1) are compatible.
    - (3,1) and (2,2) are not compatible.

In [28]:
import numpy as np 

var1=np.array([[1],[2],[3]])
var2=np.array([[2,2],[3,1]])


print(var1+var2)

ValueError: operands could not be broadcast together with shapes (3,1) (2,2) 

- If the arrays have different numbers of dimensions, the smaller array is padded with ones on its left side.

In [27]:
import numpy as np


array1 = np.array([[1, 2, 3], [4, 5, 6]])  
array2 = np.array([10, 20, 30])  

print(array1 + array2)

[[11 22 33]
 [14 25 36]]


In [34]:
import numpy as np


array1 = np.array([[1, 2, 3], [4, 5, 6],[1, 2, 3]])  
array2 = np.array([1,2,3])  

print(array1 + array2)

[[2 4 6]
 [5 7 9]
 [2 4 6]]
