# Indexing
- We can access an element with any of the positive or negative indexing.


### Indexing in 1 D array

In [1]:
import numpy as np 

arr=np.array([1,2,3,4,5])

print(arr[4])
print(arr[-1])

5
5


### Indexing in 2 D array

In [2]:
import numpy as np 

arr=np.array([[1,2,3],[4,5,6]])

print(arr[1,1])
print(arr[-1,-2])

5
5


### Indexing in 3 D array

In [4]:
import numpy as np 

arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(arr)
print()
print(arr[1,0,1])
print(arr[-1,-2,-2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

8
8


# Slicing

### 1 D array slicing.
- In this, Start, Stop , and Step values are provided as the arguement in the array name.
- We can also provide the negative index numbers.
- Default value of the Start is 0, Stop is *Length* -1, and Step is 1.

In [9]:
import numpy as np 

arr=np.array([1,2,3,4,5,6,7,8,9,10])

print("From value 2 to value 5:",arr[1:5:1])


From value 2 to value 5: [2 3 4 5]


In [10]:
# Printing Reverse Arrray
import numpy as np 

arr=np.array([1,2,3,4,5,6,7,8,9,10])

print("Reversed Array:",arr[::-1])

From value 2 to value 5: [10  9  8  7  6  5  4  3  2  1]


In [1]:
import numpy as np 

arr=np.array([1,2,3,4,5,6,7,8,9,10])

print("From value 10 to value 5:",arr[9:3:-1])

From value 10 to value 5: [10  9  8  7  6  5]


### 2D array slicing
- We just have to bring the control to the row, from which we want to print the values, and after that we have to provide Start, Stop, and Step values.

In [2]:
import numpy as np 

arr=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

print(arr)
print()
print("From value 7 to value 10:",arr[1,1:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

From value 7 to value 10: [ 7  8  9 10]


### 3 D array slicing
- Similar to 2 D array, bring control to the required row and provide the values of Start, Stop, and Step.

In [18]:
import numpy as np 

arr=np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]]])

print(arr)
print()
print("From value 12 to value 15",arr[1,0,1:])

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]

From value 12 to value 15 [12 13 14 15]
