# Join and split numpy arrays


## Joining two 1 D arrays

In [5]:
import numpy as np
var1=np.array([1,2,3,4,5])
var2=np.array([6,7,8,9,10])

var3=np.concatenate((var1,var2))

print("New Array:",var3)


New Array: [ 1  2  3  4  5  6  7  8  9 10]


# Joining two 2 D arrays
- With concatenate() function, axis value is also provided in the mukti m=dimension array.
- axis=0 for column wise concatenation
- axis=1 for row wise concatenation


In [5]:
import numpy as np

var1=np.array([[1,2],[3,4]])
var2=np.array([[5,6],[7,8]])

var3=np.concatenate((var1,var2), axis=0)

print(var1)
print()
print(var2)
print()

print("Column wise concatination:",var3)
print()

print("Row wise concatination:",np.concatenate((var1,var2),axis=1))

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

Column wise concatination: [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Row wise concatination: [[1 2 5 6]
 [3 4 7 8]]


## Joining two 1 D arrays using stack() function

In [8]:
import numpy as np

var1=np.array([1,2,3,4])
var2=np.array([5,6,7,8])

print("Column wise conactenation:\n",np.stack((var1,var2),axis=0))
print()
print("Row wise concatenation:\n",np.stack((var1,var2),axis=1))

Column wise conactenation:
 [[1 2 3 4]
 [5 6 7 8]]

Row wise concatenation:
 [[1 5]
 [2 6]
 [3 7]
 [4 8]]


## Joining two 2 D arrays using stack() function

In [12]:
import numpy as np

var1=np.array([[1,2],[3,4]])
var2=np.array([[5,6],[7,8]])

print("Column wise conactenation:\n",np.stack((var1,var2),axis=0))
print()
print("Row wise concatenation:\n",np.stack((var1,var2),axis=1))

Column wise conactenation:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

Row wise concatenation:
 [[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


- We can use vstack to concatente arrays along column wise and hstack along row wise.
- dstack is used to concatenate height wise.

In [16]:
import numpy as np

var1=np.array([[1,2],
               [3,4]])
var2=np.array([[5,6],
               [7,8]])

print("Column wise conactenation:\n",np.vstack((var1,var2)))
print()
print("Row wise concatenation:\n",np.hstack((var1,var2)))
print()
print("Height wise concatenation:\n",np.dstack((var1,var2)))

Column wise conactenation:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Row wise concatenation:
 [[1 2 5 6]
 [3 4 7 8]]

Height wise concatenation:
 [[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


🔔Note: stac() and concatenate() serves differently.
np.stack introduces a new axis, while np.concatenate operates along an existing axis without adding a new one. The choice between them depends on whether you want to introduce a new axis or concatenate along an existing one.


## Spliting 1 D array

In [18]:
import numpy as np

var1=np.array([1,2,3,4,5,6])

var2=np.array_split(var1,4)

print(var1)
print(type(var1))
print(var2)
print(type(var2))
print(var2[0])

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
[array([1, 2]), array([3, 4]), array([5]), array([6])]
<class 'list'>
[1 2]


## Spliting 2 D array

In [22]:
import numpy as np

var1=np.array([[1,2],[3,4],[5,6]])

var2=np.array_split(var1,3)

print(var1)
print(type(var1))
print(var2)
print(type(var2))
print(var2[0])

[[1 2]
 [3 4]
 [5 6]]
<class 'numpy.ndarray'>
[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]
<class 'list'>
[[1 2]]
