# Searching

## where()
- It returned the locations in the term of index number where the element is found.

In [4]:
import numpy as np

var1=np.array([1,2,3,4,5,6,7,8])

position=np.where((var1%2)==0)

print(position)

(array([1, 3, 5, 7], dtype=int64),)


## searchsorted()
- This function perform the binary search over a sorted array and then return the location in term of index number where we cann insert that element.

In [4]:
import numpy as np

var1=np.array([1,2,3,4,6,7,8])

position=np.searchsorted(var1,5)

print(position)

4


- We can ask for multiple elements at once.

In [5]:
import numpy as np

var1=np.array([1,3,4,6,8])

positions=np.searchsorted(var1,[2,5,7])

print(positions)

[1 3 4]


# Sorting

## sort()
- This function is used to sort the array element in ascending or descending order based on numeric or alphabetical order.

In [15]:
import numpy as np

var1=np.array([2,5,1,99,3,2])
var2=np.array(['s','a','t','b','e'])

print(np.sort(var1))
print(np.sort(var2))

[ 1  2  2  3  5 99]
['a' 'b' 'e' 's' 't']


- Sorting the 2 D array.

In [16]:
import numpy as np

var1=np.array([[2,5,1],[99,3,2]])
var2=np.array([['s','a','t'],['b','e','z']])

print(np.sort(var1))
print(np.sort(var2))

[[ 1  2  5]
 [ 2  3 99]]
[['a' 's' 't']
 ['b' 'e' 'z']]


# Filtering
- In this method filter array is created that is used afterward to filter the array element.
- Corressponding elements to True are accepted and False one are discarded.

In [2]:
import numpy as np

array=np.array(["Ram","Ravan","Vibhishan","Sita","Lakshman"])

filter1=[True,False,False,True,True]

filtered_array=array[filter1]
print(filtered_array)
print(type(filtered_array))

['Ram' 'Sita' 'Lakshman']
<class 'numpy.ndarray'>
