# Arithmetic Functions


## shuffle()
- It is used to shuffle the array elements.

In [1]:
import numpy as np

var1=np.array([1,2,3,4,5])
np.random.shuffle(var1)

print(var1)

[3 1 2 5 4]


## unique()
- This function make an array of elements, taking only one time each, of the array.
- Apart from that we can also get the index locations of the elements and we can also count them.

In [3]:
import numpy as np

var1=np.array([1,2,3,2,3,4,6,7,8])

var2=np.unique(var1,return_index=True,return_counts=True)

print(var2)

(array([1, 2, 3, 4, 6, 7, 8]), array([0, 1, 2, 5, 6, 7, 8], dtype=int64), array([1, 2, 2, 1, 1, 1, 1], dtype=int64))


## resize()
- As its name suggest, it resize the 1 D array. 

In [4]:
import numpy as np

var1=np.array([1,2,3,4,5,6,7,8])

var2=np.resize(var1,(2,4))

print(var2)

[[1 2 3 4]
 [5 6 7 8]]


## flatten() and ravel()
- These function is used to convert multi dimensional array into 1 dimension. There are many orders: C (default), F, A, K
- By default order is C


In [11]:
import numpy as np

var1=np.array([[1,2,3,4],[5,6,7,8]])

var2=var1.flatten()
var3=var1.flatten(order="F")

print(var1)
print()
print(var2)
print()
print(var3)

[[1 2 3 4]
 [5 6 7 8]]

[1 2 3 4 5 6 7 8]

[1 5 2 6 3 7 4 8]


In [12]:
import numpy as np

var1=np.array([[1,2,3,4],[5,6,7,8]])

var2=var1.ravel()
var3=var1.ravel(order="F")

print(var1)
print()
print(var2)
print()
print(var3)

[[1 2 3 4]
 [5 6 7 8]]

[1 2 3 4 5 6 7 8]

[1 5 2 6 3 7 4 8]


### Notice🔔
Both the functions,flatten and ravel looks same but they are different as like copy and view. flatten function create a separate copy of the array, while ravel just create an another tag for the same array.

In [15]:
import numpy as np

var1=np.array([[1,2,3,4],[5,6,7,8]])

var2=var1.flatten()
var2[1]=22

print("Original:",var1)
print()
print("New:",var2)

Original: [[1 2 3 4]
 [5 6 7 8]]

New: [ 1 22  3  4  5  6  7  8]


In [14]:
import numpy as np

var1=np.array([[1,2,3,4],[5,6,7,8]])

var2=var1.ravel()
var2[1]=22

print("Original:",var1)
print()
print("New:",var2)


Original: [[ 1 22  3  4]
 [ 5  6  7  8]]

New: [ 1 22  3  4  5  6  7  8]
