# Insertion

## insert() function
- This function take 3 parameters: 
1. The array's name in which you want to insert the elements.
2. The position at which you want to insert the elements.
3. The value you want to insert.

In [2]:
import numpy as np

var1=np.array([1,2,4,5,6])

var2=np.insert(var1,2,3)

print(var2)

[1 2 3 4 5 6]


- We can add multiple elements at once.

In [3]:
import numpy as np

var1=np.array([1,2,4,5,7,9])

var2=np.insert(var1,(2,4,5),(3,6,8))

print(var2)

[1 2 3 4 5 6 7 8 9]


### Notice🔔
If we want to insert the float value, then it will first convert the float value into int and then insert it.

In [4]:
import numpy as np

var1=np.array([1,2,4,5,6,7])

var2=np.insert(var1,2,3.5)

print(var2)

[1 2 3 4 5 6 7]


## Inserting elements in 2 D array

- We can either insert the elements in row or column:
1. axis=0, for column wise insertion
2. axis=1, for row wise insertion

- If we provide only 1 element, then that same element will be converted into row or column and then inserted into the array.

In [6]:
# Inserting single element 1 D array in 2 D matrix

import numpy as np

var1=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])        


var2=np.insert(var1,1,2, axis=0)                          # columwise insertion
var3=np.insert(var1,4,5, axis=1)                          # rowise insertion
print(var2)
print()
print(var3)

[[ 1  2  3  4]
 [ 2  2  2  2]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 1  2  3  4  5]
 [ 5  6  7  8  5]
 [ 9 10 11 12  5]]


In [7]:
# Inserting multi element 1 D array in 2 D matrix

import numpy as np

var1=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])        


var2=np.insert(var1,1,[10,20,30,40], axis=0)                          # columwise insertion
var3=np.insert(var1,4,[100,200,300], axis=1)                          # rowise insertion
print(var2)
print()
print(var3)

[[ 1  2  3  4]
 [10 20 30 40]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[  1   2   3   4 100]
 [  5   6   7   8 200]
 [  9  10  11  12 300]]


## append() function
- This function is used to add the element at the end of the array i.e. it doesn't need the position parameter.
- Through this function we can directly add the float value.

In [8]:
# Adding element to 1 D array

import numpy as np

var1=np.array([1,2,3,4])

var2=np.append(var1,5.5)

print(var2)

[1.  2.  3.  4.  5.5]


In [14]:
import numpy as np

var1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Column-wise insertion
var2 = np.append(var1, [[3, 3, 3, 3]], axis=0)  # Note the extra square brackets around [3, 3, 3, 3]

# Row-wise insertion
var3 = np.append(var1, [[5], [5], [5]], axis=1)  # Note the extra square brackets around each row [5], [5], [5]

print(var2)
print()
print(var3)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 3  3  3  3]]

[[ 1  2  3  4  5]
 [ 5  6  7  8  5]
 [ 9 10 11 12  5]]


# Deletion


## delete() function
- Can be applied for the 1 D as well as multi dimensional array.
- Two parameters are passed:
1. First one is the array name
2. Second one is the index of that element

In [17]:
# Deleting 1 D array element
import numpy as np

var1=np.array([1,2,3,4,5,6,7])

var2=np.delete(var1,3)

print(var2)

[1 2 3 5 6 7]


In [21]:
# Deleting row and column of 2 D array
import numpy as np

var1=np.array([[1,2,3],[4,5,6],[7,8,9]])

var2=np.delete(var1,2,axis=0)                   # Deleting row
var3=np.delete(var1,1,axis=1)                   # Deleting column

print(var2)
print()
print(var3)

[[1 2 3]
 [4 5 6]]

[[1 3]
 [4 6]
 [7 9]]
