# Matrix in NumPy
- Matrix and 2 D array both looks similar in Numpy. But they are different.

## Creating Matrix


In [1]:
import numpy as np 

var1=np.matrix([[1,2,3],[4,5,6]])

print(type(var1))
print(var1)

<class 'numpy.matrix'>
[[1 2 3]
 [4 5 6]]


In [3]:
import numpy as np 

var1=np.array([[1,2,3],[4,5,6]])

print(type(var1))
print(var1)

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]


## Arithmetic operations in Matrix

### Addition

In [4]:
import numpy as np

var1=np.array([[1,2,3],[4,5,6]])

var1=var1+2

print(var1)

[[3 4 5]
 [6 7 8]]


In [6]:
import numpy as np

var1=np.array([[1,2,3],[4,5,6]])
var2=np.array([[10,20,30],[40,50,60]])

var3=var1+var2

print(var3)

[[11 22 33]
 [44 55 66]]


## Subtraction

In [7]:
import numpy as np

var1=np.array([[1,2,3],[4,5,6]])
var2=np.array([[10,20,30],[40,50,60]])

var3=var2+var1

print(var3)

[[11 22 33]
 [44 55 66]]


## Multiplication
- Here comes an important point, 2D array and matrix get multiplied differently.
- In 2D array, corresponding elements get multiplied.
- While in matrix, they are multiplied as like in Mathematics.
- dot() function is used for matrix multiplication.

In [8]:
import numpy as np

var1=np.array([[1,2,3],[4,5,6]])
var2=np.array([[10,20,30],[40,50,60]])

var3=var2*var1

print(var3)

[[ 10  40  90]
 [160 250 360]]


In [2]:
import numpy as np

var1=np.matrix([[1,2],[3,4]])
var2=np.matrix([[10,20],[30,40]])

var3=var1*var2

print(var3)
print()
print(var2.dot(var1))

[[ 70 100]
 [150 220]]

[[ 70 100]
 [150 220]]


# Functions in Matrix

## Transpose()
- It changes the axes of the matrix.
- Either we can use the transpose() function or *matrix name*.T method to transpose the matrix.

In [3]:
import numpy as np

var1=np.matrix([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print(var1)
print()
print(np.transpose(var1))
print()
print(var1.T)                                    #Another way to print the transpose of a matrix

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


## Swapaxes()
- It is also used to interchange the two axes.
## Notice 🔔
- swapaxes() specifically swaps two axes, whereas transpose() is more general and allows you to specify the new order of axes.

In [15]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

arr_swapped = np.swapaxes(arr, 0,1)

print("Original array:")
print(arr)
print("\nArray after swapping axes:")
print(arr_swapped)


Original array:
[[1 2 3]
 [4 5 6]]

Array after swapping axes:
[[1 4]
 [2 5]
 [3 6]]


## Inverse
- linalg.inv(*Matrix Name*) function is used to inverse the matrix.

In [19]:
import numpy as np

var1=np.array([[1,2,3],[5,6,7],[9,10,11]])

print(var1)
print()
print(np.linalg.inv(var1))

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]

[[ 5.62949953e+14 -1.12589991e+15  5.62949953e+14]
 [-1.12589991e+15  2.25179981e+15 -1.12589991e+15]
 [ 5.62949953e+14 -1.12589991e+15  5.62949953e+14]]


## Power
- As like squaring in math, power function is used in the numpy.
- linalg.matrix_power(*Matrix Name, n*) is the function that is used.
1. Matrix Name: It is the matrix, on which the power operation is carried out.
2. n: There may be 3 possible cases:
   - n<0: It first inverse the matrix, then apply the power.
   - n=0: It return the unit matrix of the same order.
   - n>0: It directly apply the power over the matrix.

In [20]:
import numpy as np

var1=np.array([[1,2,3],[5,6,7],[9,10,11]])

print(np.linalg.matrix_power(var1,-2))                 #n<0
print()
print(np.linalg.matrix_power(var1,0))                 #n=0
print()
print(np.linalg.matrix_power(var1,2))                 #n>0


[[ 1.9014759e+30 -3.8029518e+30  1.9014759e+30]
 [-3.8029518e+30  7.6059036e+30 -3.8029518e+30]
 [ 1.9014759e+30 -3.8029518e+30  1.9014759e+30]]

[[1 0 0]
 [0 1 0]
 [0 0 1]]

[[ 38  44  50]
 [ 98 116 134]
 [158 188 218]]


## Determinate
- To determine the determinate, we use linalg.det(*Matrix Name*) function.
- It is calcualted on square matrix.

In [7]:
# Determinate of 2x2 matrix
import numpy as np 

var1=np.array([[23,45],[67,89]])

print(np.linalg.det(var1))

-967.9999999999997


In [8]:
# Determinate of 3x3 matrix
import numpy as np 

var1=np.array([[1,2,3],[4,5,6],[7,8,9]])

print(np.linalg.det(var1))

0.0
