# Creating array from list
- If we directly give the name of the variable it shows its type as well (Only in Jupyter Notebook.)

In [6]:
import numpy as np 
list1=[1,2,3,4,5]
a=np.array(list1)
print(type(a))
print(a)
a

<class 'numpy.ndarray'>
[1 2 3 4 5]


array([1, 2, 3, 4, 5])

# Creating array from tuple

In [7]:
tuple1=(1,2,3,4,5,)
b=np.array(tuple1)
print(type(b))
print(b)
b

<class 'numpy.ndarray'>
[1 2 3 4 5]


array([1, 2, 3, 4, 5])

# Making the array by taking input from the user.

In [8]:
import numpy as np

list1=[]
for i in range (5):
    var=int(input("Enter the number:"))
    list1.append(var)

print(np.array(list1))

[3 4 4 5 6]


# Creating multidimensional array and *ndim* and *ndmin* functions use.
- For creating the multidimensional array, you just have to add teh equal amount of big bractes '[]' in the starting and ending.
- But this approach  is good for small dimensions, for big arrays *ndmin* function is used.
- To find the dimention, one can count the big bractes or just use the *ndim* function.

In [16]:
import numpy as np 
arr_4=np.array([[[[1,2,3,4,5],[6,7,8,9,10]]]])
print(arr_4)
print("Dimension :",arr_4.ndim)


[[[[ 1  2  3  4  5]
   [ 6  7  8  9 10]]]]
Dimension : 4


In [17]:
arr_10=np.array([[1,2,3,4,5],[6,7,8,9,10]],ndmin=10)
print(arr_10)
print("Dimenion :",arr_10.ndim)

[[[[[[[[[[ 1  2  3  4  5]
         [ 6  7  8  9 10]]]]]]]]]]
Dimenion : 10
