# Special Array Functions

### rand() Function
- The function is used to generate a random value between 0 and 1.

In [10]:
import numpy as np

var1_rand=np.random.rand(5)
var2_rand=np.random.rand(3,5)
print(var1_rand)
print("\n",var2_rand)

[0.93051748 0.01925052 0.91774705 0.64079795 0.51964645]

 [[0.7196131  0.31020483 0.45711057 0.49191188 0.56364278]
 [0.64235193 0.44701326 0.04492185 0.49959636 0.26945262]
 [0.46771895 0.84748365 0.10589977 0.11204198 0.171352  ]]


### randn() Function
- This function is used to generate the value close to zero. Returned values may be positive or negative.

In [2]:
var1_randn=np.random.randn(5)
var2_randn=np.random.randn(3,4)
print(var1_randn)
print()
print(var2_randn)

[ 0.43674363 -1.30374587  0.28029766  1.38237322  0.2074817 ]

[[-1.72185675 -0.711506    1.40199256  0.83483644]
 [ 0.66039249  0.96473567 -0.98134529 -0.46383977]
 [-0.28258919  1.13740258  0.36748318 -0.55664747]]


### ranf() Function
- The function for doing random sampling in numpy. It returns an array of specified shape and fills it with random floats in the half open interval [0.0, 1.0).


In [4]:
var1_ranf=np.random.ranf(5)
var2_ranf=np.random.ranf((3,4))
print(var1_ranf)
print()
print(var2_ranf)

[0.70612755 0.16891973 0.82731835 0.66259093 0.60973737]

[[0.33830018 0.9006282  0.56078774 0.31500673]
 [0.84143869 0.7322875  0.10204397 0.17613841]
 [0.98854033 0.58697404 0.54287243 0.77442555]]


### randint() Function
- The function is used to generate a random number array between a given range.

In [13]:
import numpy as np
var1_randint=np.random.randint(1,5,12)
var2_randint=var1_randint.reshape((3,4))
print(var1_randint)
print()
print(var2_randint)

[1 1 4 3 2 3 3 2 3 3 4 4]

[[1 1 4 3]
 [2 3 3 2]
 [3 3 4 4]]
