# Shape in NumPy array.

In [1]:
import numpy as np 

var=np.array([[1,2],[3,4]])

print(var)
print()
print(var.shape)

[[1 2]
 [3 4]]

(2, 2)


- ndim= to print the dimension of the array.
- ndmin= to set the dimension of the array.


In [4]:
import numpy as np

var1=np.array([[1,2,3,4],[3,4,5,6]],ndmin=6)

print(var1)
print()
print("Dimension:",var1.ndim)
print()
print(var1.shape)


[[[[[[1 2 3 4]
     [3 4 5 6]]]]]]

Dimension: 6

(1, 1, 1, 1, 2, 4)


# Reshape in Numpy array.


In [7]:
import numpy as np

var1=np.array([1,2,3,4,5,6,7,8,9,10,11,12])

print(var1)
print()
print(var1.shape)
print()

var2=var1.reshape(6,2)

print(var2)
print()
print(var2.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]

(12,)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]

(6, 2)


# Creating a 3 dimensional array from 1 dmensional and then converting it back to 1 dimensional.
- -1 arguemnet is passed to reshape function to convert any array to 1 dimension.

In [13]:
import numpy as np

arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])

print(arr)
print("Dimension:",arr.ndim)                              # 1 dimensional
print()

arr1=arr.reshape(2,3,2)
print(arr1)
print("Dimension:",arr1.ndim)                             # 3 dimensional
print()

arr2=arr1.reshape(-1)
print(arr2)
print("Dimension:",arr2.ndim)                             # 1 dimensional



[ 1  2  3  4  5  6  7  8  9 10 11 12]
Dimension: 1

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
Dimension: 3

[ 1  2  3  4  5  6  7  8  9 10 11 12]
Dimension: 1
